---
abstract: 'SQLite3 store for NIST::NVD'
author:
  - 'C.J. Adams-Collier <cjac@f5.com>'
build_requires:
  Perl::Critic: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  XML::XPath: 0
  XML::XPath::XMLParser: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NIST-NVD-Store-SQLite3
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 0
  DBI: 0
  NIST::NVD: 1
  Time::HiRes: 0
  XML::XPath: 0
version: v1.00.00
